unit: option/inventory/half
in: option/inventory
name: "Inventory (half size)"

inc:
  - at: '@pages'
    add:
      - page: inventory
        order: 15
        flex: true
        landscape: true
        contents:
          - layout: 2e
            contents:
              - g:
                contents:
                  - layout: 2e
                    contents:
                      - g:
                        contents:
                          - section: "Inventory"
                            contents:
                              - list:
                                zebra: true
                                collapse: true
                                field_frame: none
                                contents:
                                  - repeat: 24
                                    contents:
                                      - row:
                                        contents:
                                          - field: inventory-#{i}
                                            width: stretch
                                          - field: inventory-#{i}-value
                                          - field: inventory-#{i}-weight
                              - g:
                                contents:
                                  - field: weight-total
                                    frame: left
                                    label: "Total weight"
                                    border: none
                                    control: weight
                                    # width: huge
                              - hr:
                              - h5: "Expendables"
                              - list:
                                zebra: true
                                collapse: true
                                field_frame: none
                                contents:
                                  - repeat: 2
                                    merge-bottom: true
                                    contents:
                                      - row:
                                        contents:
                                          - field: expendable-#{i}
                                            width: stretch
                                          - field: expendable-#{i}-count
                                            frame: none
                                            control: checkgrid
                                            max: 20
                                            depth: 3
                                            
                          - g:
                            contents:
                              - hr:
                              - h5: "Money"
                              - field: money-platinum
                                frame: left
                                control: money
                                label: "Platinum"
                                denomination: platinum
                                digits: 7
                                shift: 3
                              - field: money-gold
                                frame: left
                                control: money
                                label: "Gold"
                                denomination: gold
                                digits: 8
                                shift: 2
                              - field: money-silver
                                frame: left
                                control: money
                                label: "Silver"
                                denomination: silver
                                digits: 9
                                shift: 1
                              - field: money-copper
                                frame: left
                                control: money
                                label: "Copper"
                                denomination: copper
                                digits: 10
                              - field: money-total
                                frame: left
                                output: 'true'
                                control: money
                                legend: "Total"
                                denomination: copper
                                digits: 10
                                decimal: 1
                              - p: "1000 coins = 1 bulk"
                          - tail:
                      - g:
                        contents:
                          - section: "Worn Equipment"
                            contents:
                              - list:
                                zebra: true
                                flex: true
                                hr: true
                                # avoid-shade: true
                                contents:
                                  - repeat: 10
                                    contents:
                                      - level: '#{i}'
                                        marker: ''
                                        contents:
                                          - article:
                                            lines: 1
                                            
                          - section: "Armour"
                            contents:
                              - row:
                                layout: split
                                contents:
                                  - field: armour
                                    frame: none
                                    size: large
                                    width: stretch
                                  - field: armour-bulk
                                    label: "Bulk"
                                  - field: armour-ac
                                    label: "AC Bonus"
                                    icon: ac
                                    border: full
                              - row:
                                layout: split
                                contents:
                                  - field: armour-cat
                                    label: "Category"
                                    width: stretch
                                  - field: armour-dex-cap
                                    label: "DEX\nCap"
                                  - field: armour-acp
                                    label: "Check\nPenalty"
                              - field: armour-properties
                                width: stretch
                                label: "Armour Traits"
                                repeat: 2
                                merge-bottom: true

                          - section: "Shield"
                            contents:
                              - row:
                                layout: split
                                contents:
                                  - field: shield
                                    frame: none
                                    size: large
                                    width: stretch
                                  - field: shield-bulk
                                    label: "Bulk"
                                  - field: shield-ac
                                    label: "AC Bonus"
                                    icon: ac
                                    border: full
                              - row:
                                contents:
                                  - field: shield-hardness
                                    label: "Hardness"
                                    width: large
                                    overlay: "hp"
                                  - spacer:
                                  - field: shield-bt
                                    label: "Broken\nThreshold"
                                    overlay: "hp"
                                    width: large
                                  - spacer:
                                  - field: shield-hp
                                    label: "Hit Points"
                                    icon: hp
                                    border: full
                                    width: large
                                    overlay: "hp"
                              - field: armour-properties
                                width: stretch
                                label: "Shield Traits"
                                repeat: 2
                                merge-bottom: true

                          - tail:

