unit: option/inventory/half
in: option/inventory
name: "_{Inventory (half size)}"

inc:
  - at: '@pages'
    add:
      - page: inventory
        order: 15
        flex: true
        landscape: true
        contents:
          - layout: 2e
            contents:
              - g:
                contents:
                  - layout: 2e
                    contents:
                      - g:
                        contents:
                          - section: "_{Inventory}"
                            contents:
                              - list:
                                zebra: true
                                collapse: true
                                field_frame: none
                                contents:
                                  - repeat: 24
                                    reduce: 6
                                    contents:
                                      - row:
                                        contents:
                                          - field: inventory-#{i}
                                            width: stretch
                                          - field: inventory-#{i}-value
                                          - field: inventory-#{i}-weight
                              - g:
                                contents:
                                  - field: weight-total
                                    frame: left
                                    label: "_{Total weight}"
                                    border: none
                                    control: weight
                                    # width: huge
                              - p: "_{10 light = 1 bulk}"
                              - hr:
                              - h5: "_{Expendables}"
                              - list:
                                zebra: true
                                collapse: true
                                field_frame: none
                                merge-bottom: true
                                contents:
                                  - repeat: 2
                                    contents:
                                      - row:
                                        contents:
                                          - field: expendable-#{i}
                                            width: stretch
                                          - field: expendable-#{i}-count
                                            frame: none
                                            control: checkgrid
                                            max: 20
                                            depth: 3
                                            
                          - g:
                            contents:
                              - hr:
                              - h5: "_{Money}"
                              - field: money-platinum
                                frame: left
                                control: money
                                label: "_{Platinum}"
                                denomination: platinum
                                digits: 7
                                shift: 3
                              - field: money-gold
                                frame: left
                                control: money
                                label: "_{Gold}"
                                denomination: gold
                                digits: 8
                                shift: 2
                              - field: money-silver
                                frame: left
                                control: money
                                label: "_{Silver}"
                                denomination: silver
                                digits: 9
                                shift: 1
                              - field: money-copper
                                frame: left
                                control: money
                                label: "_{Copper}"
                                denomination: copper
                                digits: 10
                              - field: money-total
                                frame: left
                                output: 'true'
                                control: money
                                legend: "_{Total}"
                                denomination: copper
                                digits: 10
                                decimal: 1
                              - p: "_{1000 coins = 1 bulk}"
                          - tail:
                      - g:
                        contents:
                          - section: "_{Worn Equipment}"
                            contents:
                              - list:
                                zebra: true
                                flex: true
                                hr: true
                                avoid-shade: true
                                contents:
                                  - repeat: 10
                                    reduce: 2
                                    contents:
                                      - level: '#{i}'
                                        marker: ''
                                        contents:
                                          - article:
                                            lines: 1
                                            
                          - section: "_{Armour}"
                            contents:
                              - row:
                                layout: split
                                contents:
                                  - field: armour
                                    frame: none
                                    size: large
                                    width: stretch
                                  - field: armour-bulk
                                    label: "_{Bulk}"
                                  - field: armour-ac
                                    label: "_{AC Bonus}"
                                    icon: ac
                                    border: full
                              - row:
                                layout: split
                                contents:
                                  - field: armour-cat
                                    label: "_{Category}"
                                    width: stretch
                                  - field: armour-dex-cap
                                    label: "_{DEX\nCap}"
                                  - field: armour-acp
                                    label: "_{Check\nPenalty}"
                              - field: armour-properties
                                width: stretch
                                label: "_{Armour Traits}"
                                repeat: 2
                                reduce: 1
                                merge-bottom: true

                          - section: "_{Shield}"
                            contents:
                              - row:
                                layout: split
                                contents:
                                  - field: shield
                                    frame: none
                                    size: large
                                    width: stretch
                                  - field: shield-bulk
                                    label: "_{Bulk}"
                                  - field: shield-ac
                                    label: "_{AC Bonus}"
                                    icon: ac
                                    border: full
                              - row:
                                contents:
                                  - field: shield-hardness
                                    label: "_{Hardness}"
                                    width: large
                                    overlay: "_{hp}"
                                  - spacer:
                                  - field: shield-bt
                                    label: "_{Broken\nThreshold}"
                                    overlay: "_{hp}"
                                    width: large
                                  - spacer:
                                  - field: shield-hp
                                    label: "_{Hit Points}"
                                    icon: hp
                                    border: full
                                    width: large
                                    overlay: "_{hp}"
                              - field: armour-properties
                                width: stretch
                                label: "_{Shield Traits}"
                                repeat: 2
                                reduce: 1
                                merge-bottom: true

                          - tail:

